---
# tasks file for mysql_db

- name: Install MySQL ecosystem
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client


- name: Start MySQL service
  shell: 'service mysql status || true && service mysql start && service mysql status'
  args:
    warn: false
  register: mysql_service_out
  failed_when: "'Uptime:' not in mysql_service_out.stdout"
  changed_when: "'MySQL is stopped' in mysql_service_out.stdout"


- name: Create app DB
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create DB user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'


